import './globals.css';
import type { Metadata } from 'next';
export const metadata: Metadata = {
  title: 'Admin Panel',
  description: 'Generated by preeti',
}
export default function RootLayout({children}: {children: React.ReactNode}){
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
